### ISSUE TITLE
Up Down Limitierung fehlerhaft

### ISSUE THREAD

**Issue by DasNordlicht** [Freifunk-Nord/nord-site#11]
Der Eintrag in der site.conf

```
simple_tc = {
    mesh_vpn = {
        ifname = 'mesh-vpn',
        enabled = false,
        limit_egress = 800,
        limit_ingress = 4000,
    },
},
```

greift nicht richtig.
Ich erhalte ohne die Begrenzung einzuschalten 1-2 MBit/s Down und 0,2 MBit/s up.
Stelle ich nun auf eine aktive Begrenzung um und gebe dieser 16000 Down und 2000 Up, also Werte größer gleich dem DSL Limit erreiche ich 8,5 - 10 MBit/s Down und 0,7 - 1,2 MBit/s Up.
Getestet am WR1043nd V2

**Comment by rubo77** [comment]
bitte noch mal testen, das erscheint mir unlogisch, wieso sollte ohne bandbreitenbegrenzung im Router angeschaltet dieser die Bandbreite dann trotzdem begrenzen?

**Comment by DasNordlicht** [comment]
Ich habe das heute mehrfach getestet mit immer dem selbern Ergebnis.
Keiner hat behauptet das es logisch ist.

**Comment by Tarnatos** [comment]
Mit welchem Gluon Branch wurde das getestet?

**Comment by DasNordlicht** [comment]
Die aktuelle FFNord 0.7.2 müsste also gluon 15.1.x sein.

**Comment by DasNordlicht** [comment]
Es scheint am GW0 zu liegen.
Habe heute viel getestet und habe nun das GW0 in der /etc/config/fastd deaktiviert.
Nun bleibt die Geschwindigkeit konstant hoch.
