### ISSUE TITLE
Readme anpassen

### ISSUE THREAD

**Issue by rubo77** [Freifunk-Nord/nord-site#4]
Dort sollte rein:
- letzte Version
- Link zu einem Firmware download mirror
- ... und was einem noch einfällt, halt ein bischen hübsch machen

Am besten entsprechend diesem Readme erweitern: https://github.com/ffmus/site-ffwaf/blob/master/README.md

**Comment by Tarnatos** [comment]
Done:
https://github.com/ffnord/nord-site/issues/4
